ALTER PROCEDURE [ABSSP_ADMIN_VEHICLE_DETAILS_RPT]
	(@RPT_ST_DATE	DATETIME 
	,@RPT_END_DATE	DATETIME 
	,@RPT_ST_VEH_NO	CHAR(15) 
	,@RPT_END_VEH_NO CHAR(15))

AS
  SELECT 
     WK.ADM_VEH_MAINT_VEH_NO AS RPT_VEH_NO
    ,WK.ADM_VEH_MAINT_VEH_TYPE AS RPT_VEH_TYP
   -- ,WK.ADM_VEH_MAINT_TRANS_NO AS RPT_VEH_TRANS_NO
    ,WK.ADM_VEH_MAINT_TRANS_DATE AS RPT_DATE
    ,WK.ADM_VEH_MAINT_BRANCH_CODE AS RPT_BRANCH_CODE
    ,WK.ADM_VEH_MAINT_DEPT_CODE AS RPT_DEPT_CODE
    ,WK.ADM_VEH_MAINT_USER_NAME AS RPT_VEH_USER
    ,WK.ADM_VEH_MAINT_TRANS_DESC AS RPT_VEH_DESC
    ,WK.ADM_VEH_MAINT_SERVICE_COY AS RPT_SERVICE_COY
    ,WK.ADM_VEH_MAINT_TRANS_AMT AS RPT_TRANS_AMT
    ,(SELECT CTBRA_NAME FROM [ABSBRNCHTAB] WHERE CTBRA_NUM = WK.ADM_VEH_MAINT_BRANCH_CODE)AS RPT_BRANCH_NAME
    ,(SELECT CTINSRD_LONG_DESCR FROM ABSDEPTTAB WHERE CTINSRD_NO = wk.ADM_VEH_MAINT_DEPT_CODE) AS RPT_DEPT_NAME
    , USERS.ADM_TAB_ITEM_DESC AS RPT_VEH_USER
    , USERS.ADM_COD_TRANS_TYPE AS RPT_VEH_TYPE
    , INS.ADM_TAB_ITEM_DESC AS RPT_SERVICE_COY_NAME

    FROM ADM_VEH_MAINT_BILLS  AS WK

    LEFT JOIN [ADM_MAINT_CODE_TABLE]  AS USERS
       ON (USERS.ADM_TAB_ITEM_CODE_NO = ADM_VEH_MAINT_VEH_NO AND USERS.ADM_TAB_CLASS_CODE = '001')
    LEFT JOIN [ADM_MAINT_CODE_TABLE]  AS INS
       ON (INS.ADM_TAB_ITEM_CODE_NO = ADM_VEH_MAINT_SERVICE_COY AND INS.ADM_TAB_CLASS_CODE = '002')

 WHERE WK.ADM_VEH_MAINT_TRANS_DATE >= @RPT_ST_DATE AND WK.ADM_VEH_MAINT_TRANS_DATE <= @RPT_END_DATE AND
 WK.ADM_VEH_MAINT_VEH_NO >= @RPT_ST_VEH_NO AND WK.ADM_VEH_MAINT_VEH_NO <= @RPT_END_VEH_NO

    ORDER BY WK.ADM_VEH_MAINT_VEH_NO, WK.ADM_VEH_MAINT_TRANS_DATE
 







GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO
