SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

alter       PROCEDURE [ABSSP_ADMIN_TEL_REPORT]
	(@RPT_ST_DATE	DATETIME 
	,@RPT_END_DATE	DATETIME
	,@RPT_ST_BRANCH	CHAR(5)
	,@RPT_END_BRANCH CHAR(5))

AS

  SELECT WK.ADM_TELEPHONE_NO AS RPT_TEL_NO
   --  ,WK.ADM_TRANS_NO AS RPT_TRANS_NO
     ,null AS RPT_TRANS_NO
    ,WK.ADM_TRANS_DATE AS RPT_DATE
    ,WK.ADM_BRANCH_CODE AS RPT_BRANCH_CODE
    ,WK.ADM_DEPT_CODE AS RPT_DEPT_CODE
    ,WK.ADM_TRANS_DESC AS RPT_DESC
    ,WK.ADM_USER_NAME AS RPT_USER_NAME
    ,WK.ADM_TRANS_AMT AS RPT_TRANS_AMT
    ,(SELECT CTBRA_NAME FROM [ABSBRNCHTAB] WHERE CTBRA_NUM = ADM_BRANCH_CODE)AS RPT_BRANCH_NAME
    ,(SELECT CTINSRD_LONG_DESCR FROM ABSDEPTTAB WHERE CTINSRD_NUM = ADM_DEPT_CODE) AS RPT_DEPT_NAME
     ,USERS.ADM_COD_TRANS_TYPE AS RPT_TEL_TYPE

    FROM ADM_TELEPHONE_BILLS AS WK

    LEFT JOIN [ADM_MAINT_CODE_TABLE]  AS USERS
       ON (USERS.ADM_TAB_ITEM_CODE_NO = WK.ADM_TELEPHONE_NO AND USERS.ADM_TAB_CLASS_CODE= '006')

 --WHERE WK.ADM_TRANS_DATE >= @RPT_ST_DATE AND WK.ADM_TRANS_DATE <= @RPT_END_DATE AND
 --WK.ADM_BRANCH_CODE >= @RPT_ST_BRANCH AND WK.ADM_BRANCH_CODE <= @RPT_END_BRANCH

    ORDER BY WK.ADM_BRANCH_CODE, WK.ADM_TRANS_DATE





GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

