SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

Alter PROCEDURE [ABSSP_ADMIN_ELEC_REPORT]
	(@RPT_ST_DATE	DATETIME 
	,@RPT_END_DATE	DATETIME 
	,@RPT_ST_BRANCH	CHAR(5)
	,@RPT_END_BRANCH CHAR(5))

AS

  SELECT 
     WK.ADM_ELEC_METER_NO AS RPT_METER_NO
    ,WK.ADM_ELEC_ACCOUNT_NO AS RPT_ACCOUNT_NO
   -- ,WK.ADM_ELEC_TRANS_NO AS RPT_TRANS_NO
    ,WK.ADM_ELEC_TRANS_DATE AS RPT_DATE
    ,WK.ADM_ELEC_BRANCH_CODE AS RPT_BRANCH_CODE
    ,WK.ADM_ELEC_DEPT_CODE AS RPT_DEPT_CODE
    ,WK.ADM_ELEC_PERIOD_PAID_FOR AS RPT_PERIOD
    ,WK.ADM_ELEC_TRANS_AMT AS RPT_TRANS_AMT
    ,(SELECT CTBRA_NAME FROM [ABSBRNCHTAB] WHERE CTBRA_NUM = WK.ADM_ELEC_BRANCH_CODE)AS RPT_BRANCH_NAME
    ,(SELECT CTINSRD_LONG_DESCR FROM ABSDEPTTAB WHERE CTINSRD_NO = wk.ADM_ELEC_DEPT_CODE) AS RPT_DEPT_NAME
    FROM ADM_ELECTRIC_BILLS AS WK
 WHERE WK.ADM_ELEC_TRANS_DATE >= @RPT_ST_DATE AND WK.ADM_ELEC_TRANS_DATE <= @RPT_END_DATE AND
 WK.ADM_ELEC_BRANCH_CODE >= @RPT_ST_BRANCH AND WK.ADM_ELEC_BRANCH_CODE <= @RPT_END_BRANCH

    ORDER BY WK.ADM_ELEC_BRANCH_CODE, WK.ADM_ELEC_TRANS_DATE
 

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

